# Generated by Django 3.2.4 on 2021-06-06 12:53
from django.contrib.auth.hashers import make_password
from django.db import migrations


def user_admin_create(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.create(
        username="admin",
        email="admin@admin.com",
        is_superuser=True,
        is_staff=True,
        password=make_password("admin"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(user_admin_create),
    ]
