# Generated by Django 3.2.4 on 2021-06-06 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gallery.photo"
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gallery.photo"
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
